name: Use Centralized CI/CD

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  manifest-pipeline:
    uses: manifest-interview/ci-pipeline/.github/workflows/pipeline.yml@master
    with:
      skip_build: true
      external_image: aquasec/trivy:latest
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY_URI: ${{ secrets.ECR_REPOSITORY_URI }}
